export const books=[
{id:'design',title:'O Design do Dia a Dia',author:'Donald A. Norman',type:'Livro',color:'#e66a4e',accent:'#f4d8c9',pages:368,priority:'Alta',level:'Introdutório',time:'9h',notes:42,new:true,tags:['design','usabilidade'],summary:'Uma introdução aos princípios que tornam objetos e interfaces compreensíveis, com ênfase em affordances, feedback, restrições e modelos mentais.',learn:['Identificar problemas de usabilidade','Diferenciar erro humano de falha de design','Projetar ações mais evidentes'],questions:['Como um objeto comunica sua forma de uso?','Quando um erro deve ser atribuído ao sistema?']},
{id:'cansaco',title:'Sociedade do Cansaço',author:'Byung-Chul Han',type:'Livro Amazon',color:'#344447',accent:'#bcd0cb',pages:128,priority:'Média',level:'Intermediário',time:'3h',notes:18,tags:['filosofia','sociedade'],summary:'Uma reflexão sobre desempenho, produtividade e esgotamento na sociedade contemporânea.',learn:['Reconhecer a lógica do desempenho','Relacionar produtividade e autoexploração'],questions:['Por que o excesso de positividade pode adoecer?']},
{id:'campo',title:'Pesquisa de Campo',author:'Mekora Notes',type:'PDF',color:'#d6aa4d',accent:'#f2e4b9',pages:54,priority:'Alta',level:'Prático',time:'2h',notes:9,new:true,made:true,tags:['pesquisa','ux'],summary:'Guia prático para planejar, executar e sintetizar entrevistas e observações de campo.',learn:['Preparar um roteiro flexível','Separar observação de interpretação'],questions:['Que evidências sustentam cada conclusão?']},
{id:'tipografia',title:'Elementos da Tipografia',author:'Robert Bringhurst',type:'Livro',color:'#6e5b92',accent:'#d9cfea',pages:352,priority:'Média',level:'Avançado',time:'12h',notes:31,tags:['tipografia','design'],summary:'Princípios históricos, técnicos e estéticos para tratar a linguagem escrita com precisão.',learn:['Construir hierarquia tipográfica','Escolher proporções e ritmos'],questions:['Quando a tipografia deve desaparecer?']},
{id:'interfaces',title:'Interfaces Calmas',author:'Caderno Mekora',type:'EPUB',color:'#568a7c',accent:'#cce0d9',pages:176,priority:'Alta',level:'Intermediário',time:'5h',notes:23,new:true,made:true,tags:['interface','produto'],summary:'Notas sobre produtos digitais que respeitam atenção, contexto e ritmo humano.',learn:['Reduzir ruído operacional','Criar estados de baixa ansiedade'],questions:['Quanto da interface precisa estar visível agora?']},
{id:'cidade',title:'A Imagem da Cidade',author:'Kevin Lynch',type:'Livro Amazon',color:'#527c9c',accent:'#c8dbe7',pages:240,priority:'Baixa',level:'Intermediário',time:'7h',notes:11,tags:['cidade','arquitetura'],summary:'Estudo sobre como as pessoas percebem, organizam e recordam ambientes urbanos.',learn:['Entender marcos e percursos','Analisar legibilidade espacial'],questions:['O que torna um lugar memorável?']},
{id:'sistemas',title:'Pensando em Sistemas',author:'Donella Meadows',type:'PDF',color:'#9d554b',accent:'#e7c8c1',pages:256,priority:'Alta',level:'Intermediário',time:'8h',notes:27,tags:['sistemas','estratégia'],summary:'Uma introdução acessível a estoques, fluxos, ciclos de feedback e intervenções sistêmicas.',learn:['Mapear ciclos de feedback','Encontrar pontos de alavancagem'],questions:['Qual estrutura está produzindo este comportamento?']},
{id:'cor',title:'Interação da Cor',author:'Josef Albers',type:'Livro',color:'#d44d2f',accent:'#f6bd67',pages:208,priority:'Baixa',level:'Prático',time:'6h',notes:14,tags:['cor','design'],summary:'Experimentos que mostram como a percepção da cor depende do contexto e das relações.',learn:['Perceber relatividade cromática','Construir contraste por interação'],questions:['Uma cor pode parecer duas?']},
{id:'atlas',title:'Atlas de Ideias',author:'Arquivo pessoal',type:'PDF',color:'#1f5e68',accent:'#99c9ca',pages:91,priority:'Média',level:'Exploratório',time:'3h',notes:6,new:true,tags:['referência','processo'],summary:'Coleção visual de referências, fragmentos e conexões para projetos em andamento.',learn:['Reconhecer padrões recorrentes','Transformar referências em hipóteses'],questions:['Quais ideias reaparecem em contextos diferentes?']},
{id:'forma',title:'A Forma das Coisas',author:'Vilém Flusser',type:'Livro Amazon',color:'#3c3834',accent:'#cbc2b7',pages:192,priority:'Média',level:'Avançado',time:'6h',notes:16,tags:['filosofia','design'],summary:'Ensaios sobre objetos, cultura, tecnologia e a responsabilidade de quem projeta.',learn:['Questionar a neutralidade dos objetos','Relacionar forma e intenção'],questions:['Todo objeto carrega um programa?']},
{id:'servicos',title:'Design de Serviços',author:'Marc Stickdorn',type:'EPUB',color:'#cc7464',accent:'#f0cfca',pages:384,priority:'Alta',level:'Prático',time:'11h',notes:35,tags:['serviços','produto'],summary:'Métodos e ferramentas para investigar e projetar experiências que atravessam múltiplos pontos de contato.',learn:['Mapear jornadas e bastidores','Prototipar serviços completos'],questions:['Onde a experiência muda de responsável?']},
{id:'clippings',title:'My Clippings',author:'Kindle Paperwhite',type:'Arquivo de notas',color:'#d4a33d',accent:'#f2e4b8',pages:0,priority:'Revisar',level:'147 registros',time:'6 pendentes',notes:147,special:true,tags:['anotações'],summary:'Backup versionado das anotações importadas. A maioria já está associada aos livros correspondentes; seis registros aguardam revisão.',learn:['141 anotações associadas','4 versões preservadas'],questions:['Associar as seis anotações pendentes?']}
];
