"""notas que nao vem de um trabalho daqui

Revision ID: 0f603af97357
Revises: a68989004ad5
Create Date: 2026-08-31 00:41:01.449745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f603af97357'
down_revision: Union[str, Sequence[str], None] = 'a68989004ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        # `server_default` nas duas: o `default` do modelo e aplicado pelo ORM,
        # em Python, e o banco nunca o ve. Numa coluna NOT NULL isso deixa as
        # linhas que ja existem sem valor.
        batch_op.add_column(sa.Column('origem', sa.String(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('fonte', sa.String(), nullable=False, server_default='leitura'))
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('fonte')
        batch_op.drop_column('origem')

    # ### end Alembic commands ###
