"""o canvas: notas no espaco e ligacoes

Revision ID: 1c6432ffa8fa
Revises: 0f603af97357
Create Date: 2026-08-31 00:56:22.897444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6432ffa8fa'
down_revision: Union[str, Sequence[str], None] = '0f603af97357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas_nos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('movido_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['notas.id'], name=op.f('fk_canvas_nos_nota_id_notas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_canvas_nos_pessoa_id_pessoas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'nota_id', name='uq_canvas_nos_pessoa_id')
    )
    with op.batch_alter_table('canvas_nos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvas_nos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canvas_nos_nota_id'), ['nota_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canvas_nos_pessoa_id'), ['pessoa_id'], unique=False)

    op.create_table('ligacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('de_id', sa.Integer(), nullable=False),
    sa.Column('para_id', sa.Integer(), nullable=False),
    sa.Column('como', sa.String(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['de_id'], ['notas.id'], name=op.f('fk_ligacoes_de_id_notas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['para_id'], ['notas.id'], name=op.f('fk_ligacoes_para_id_notas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_ligacoes_pessoa_id_pessoas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'de_id', 'para_id', name='uq_ligacoes_pessoa_id')
    )
    with op.batch_alter_table('ligacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ligacoes_de_id'), ['de_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ligacoes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ligacoes_para_id'), ['para_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ligacoes_pessoa_id'), ['pessoa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ligacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ligacoes_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_ligacoes_para_id'))
        batch_op.drop_index(batch_op.f('ix_ligacoes_id'))
        batch_op.drop_index(batch_op.f('ix_ligacoes_de_id'))

    op.drop_table('ligacoes')
    with op.batch_alter_table('canvas_nos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvas_nos_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_canvas_nos_nota_id'))
        batch_op.drop_index(batch_op.f('ix_canvas_nos_id'))

    op.drop_table('canvas_nos')
    # ### end Alembic commands ###
