"""os Kindles de cada pessoa

Revision ID: 2fb4008ddf9e
Revises: 841ce2608196
Create Date: 2026-08-30 23:52:14.146934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb4008ddf9e'
down_revision: Union[str, Sequence[str], None] = '841ce2608196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aparelhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('autorizado_em', sa.DateTime(), nullable=True),
    sa.Column('ultimo_envio', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_aparelhos_pessoa_id_pessoas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'endereco', name='uq_aparelhos_pessoa_id')
    )
    with op.batch_alter_table('aparelhos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aparelhos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aparelhos_pessoa_id'), ['pessoa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aparelhos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aparelhos_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_aparelhos_id'))

    op.drop_table('aparelhos')
    # ### end Alembic commands ###
