"""quem entra: pessoas, chaves e sessoes; dono e endereco publico do trabalho

Revision ID: 3c0edf96b92b
Revises: d7f119799e30
Create Date: 2026-08-30 17:58:07.374953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0edf96b92b'
down_revision: Union[str, Sequence[str], None] = 'd7f119799e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _dar_endereco_aos_que_ja_existem() -> None:
    """Preenche `token_publico` nos trabalhos criados antes desta coluna existir.

    O autogenerate escreve o ESQUEMA e nunca os DADOS — ele não tem como saber
    que uma coluna nova precisa de valor no que já está lá. Sem este passo os
    trabalhos antigos ficam com endereço nulo, e o arquivo de cada um deixa de
    ser alcançável: a coluna existiria, a estante mostraria o item, e clicar não
    abriria nada.

    Cada token é sorteado individualmente. Um valor só para todos economizaria
    tempo e daria a todos os trabalhos o mesmo endereço — que é o defeito que
    esta coluna existe para consertar.
    """
    import secrets

    conexao = op.get_bind()
    linhas = conexao.execute(sa.text("SELECT id FROM processing_jobs WHERE token_publico IS NULL")).fetchall()
    for (job_id,) in linhas:
        conexao.execute(
            sa.text("UPDATE processing_jobs SET token_publico = :t WHERE id = :i"),
            {"t": secrets.token_urlsafe(16), "i": job_id},
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoas_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_pessoas_id'), ['id'], unique=False)

    op.create_table('chaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('resumo', sa.String(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chaves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chaves_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chaves_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chaves_resumo'), ['resumo'], unique=True)

    op.create_table('sessoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('resumo', sa.String(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('encerrada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessoes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_resumo'), ['resumo'], unique=True)

    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_publico', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dono_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_processing_jobs_dono_id'), ['dono_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_token_publico'), ['token_publico'], unique=True)
        # O nome é obrigatório: o batch do SQLite recria a tabela, e só consegue
        # recriar uma restrição que saiba nomear.
        batch_op.create_foreign_key(
            'fk_processing_jobs_dono_id_pessoas', 'pessoas', ['dono_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###

    _dar_endereco_aos_que_ja_existem()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_processing_jobs_dono_id_pessoas', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_processing_jobs_token_publico'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_dono_id'))
        batch_op.drop_column('dono_id')
        batch_op.drop_column('token_publico')

    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessoes_resumo'))
        batch_op.drop_index(batch_op.f('ix_sessoes_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_sessoes_id'))

    op.drop_table('sessoes')
    with op.batch_alter_table('chaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chaves_resumo'))
        batch_op.drop_index(batch_op.f('ix_chaves_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_chaves_id'))

    op.drop_table('chaves')
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoas_id'))
        batch_op.drop_index(batch_op.f('ix_pessoas_email'))

    op.drop_table('pessoas')
    # ### end Alembic commands ###
