"""os estudos: uma pergunta e o que se reuniu

Revision ID: 432c242b7b80
Revises: 1c6432ffa8fa
Create Date: 2026-08-31 01:13:59.397812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432c242b7b80'
down_revision: Union[str, Sequence[str], None] = '1c6432ffa8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sobre', sa.Text(), nullable=False),
    sa.Column('fechado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('mexido_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_estudos_pessoa_id_pessoas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estudos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estudos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estudos_pessoa_id'), ['pessoa_id'], unique=False)

    op.create_table('estudo_notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudo_id', sa.Integer(), nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('reunida_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estudo_id'], ['estudos.id'], name=op.f('fk_estudo_notas_estudo_id_estudos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nota_id'], ['notas.id'], name=op.f('fk_estudo_notas_nota_id_notas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudo_id', 'nota_id', name='uq_estudo_notas_estudo_id')
    )
    with op.batch_alter_table('estudo_notas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estudo_notas_estudo_id'), ['estudo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estudo_notas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estudo_notas_nota_id'), ['nota_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudo_notas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estudo_notas_nota_id'))
        batch_op.drop_index(batch_op.f('ix_estudo_notas_id'))
        batch_op.drop_index(batch_op.f('ix_estudo_notas_estudo_id'))

    op.drop_table('estudo_notas')
    with op.batch_alter_table('estudos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estudos_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_estudos_id'))

    op.drop_table('estudos')
    # ### end Alembic commands ###
