"""as notas: o que a pessoa marcou e escreveu

Revision ID: 841ce2608196
Revises: bb5a1416b358
Create Date: 2026-08-30 23:24:26.032424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841ce2608196'
down_revision: Union[str, Sequence[str], None] = 'bb5a1416b358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('capitulo', sa.Integer(), nullable=False),
    sa.Column('de', sa.Integer(), nullable=False),
    sa.Column('ate', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(), nullable=False),
    sa.Column('trecho', sa.Text(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_notas_job_id_processing_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_notas_pessoa_id_pessoas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_pessoa_id'), ['pessoa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_notas_job_id'))
        batch_op.drop_index(batch_op.f('ix_notas_id'))

    op.drop_table('notas')
    # ### end Alembic commands ###
