"""as preferencias de cada pessoa

Revision ID: a68989004ad5
Revises: c54fc411aab2
Create Date: 2026-08-31 00:09:18.540654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68989004ad5'
down_revision: Union[str, Sequence[str], None] = 'c54fc411aab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_preferencias_pessoa_id_pessoas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'chave', name='uq_preferencias_pessoa_id')
    )
    with op.batch_alter_table('preferencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preferencias_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preferencias_pessoa_id'), ['pessoa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preferencias_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_preferencias_id'))

    op.drop_table('preferencias')
    # ### end Alembic commands ###
