"""onde a pessoa parou de ler

Revision ID: bb5a1416b358
Revises: 3c0edf96b92b
Create Date: 2026-08-30 20:00:26.642516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5a1416b358'
down_revision: Union[str, Sequence[str], None] = '3c0edf96b92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progressos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('capitulo', sa.Integer(), nullable=False),
    sa.Column('deslocamento', sa.Integer(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_progressos_job_id_processing_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_progressos_pessoa_id_pessoas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'job_id', name='uq_progressos_pessoa_id')
    )
    with op.batch_alter_table('progressos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progressos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progressos_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progressos_pessoa_id'), ['pessoa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progressos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progressos_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_progressos_job_id'))
        batch_op.drop_index(batch_op.f('ix_progressos_id'))

    op.drop_table('progressos')
    # ### end Alembic commands ###
