"""quantos capitulos o livro tem

Revision ID: c54fc411aab2
Revises: 2fb4008ddf9e
Create Date: 2026-08-31 00:02:27.879890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54fc411aab2'
down_revision: Union[str, Sequence[str], None] = '2fb4008ddf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progressos', schema=None) as batch_op:
        # `server_default` E OBRIGATORIO aqui, e a falta dele passa no teste.
        #
        # O `default=0` do modelo e aplicado pelo ORM, ao criar o objeto em
        # Python — o banco nunca o ve. Numa coluna NOT NULL, isso deixa a
        # migracao sem valor para as linhas que ja existem.
        #
        # E o SQLite so RECUSA `ADD COLUMN NOT NULL` sem default quando a tabela
        # tem linhas. Com ela vazia, a migracao passa; com dados dentro, falha
        # com "Cannot add a NOT NULL column with default value NULL". Ou seja:
        # funciona em banco novo e quebra em banco usado, que e exatamente o
        # inverso do que se quer descobrir cedo.
        batch_op.add_column(sa.Column('capitulos', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progressos', schema=None) as batch_op:
        batch_op.drop_column('capitulos')

    # ### end Alembic commands ###
