"""esquema inicial: o que a migracao inline construiu ao longo do tempo

Revision ID: d7f119799e30
Revises: 
Create Date: 2026-08-30 17:34:22.299656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f119799e30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('input_path', sa.String(), nullable=True),
    sa.Column('processed_pdf_path', sa.String(), nullable=True),
    sa.Column('epub_path', sa.String(), nullable=True),
    sa.Column('cover_path', sa.String(), nullable=True),
    sa.Column('selected_cover_page', sa.Integer(), nullable=True),
    sa.Column('detected_title', sa.String(), nullable=True),
    sa.Column('detected_author', sa.String(), nullable=True),
    sa.Column('detected_language', sa.String(), nullable=True),
    sa.Column('final_title', sa.String(), nullable=True),
    sa.Column('final_author', sa.String(), nullable=True),
    sa.Column('final_language', sa.String(), nullable=True),
    sa.Column('final_filename', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_scanned', sa.Boolean(), nullable=True),
    sa.Column('avg_chars_per_page', sa.Float(), nullable=True),
    sa.Column('ocr_used', sa.Boolean(), nullable=True),
    sa.Column('ocr_status', sa.String(), nullable=True),
    sa.Column('conversion_status', sa.String(), nullable=True),
    sa.Column('send_status', sa.String(), nullable=True),
    sa.Column('send_error', sa.String(), nullable=True),
    sa.Column('kindle_sent', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('input_format', sa.String(), nullable=True),
    sa.Column('processing_mode', sa.String(), nullable=True),
    sa.Column('translation_enabled', sa.Boolean(), nullable=True),
    sa.Column('source_language', sa.String(), nullable=True),
    sa.Column('target_language', sa.String(), nullable=True),
    sa.Column('translation_status', sa.String(), nullable=True),
    sa.Column('translation_error', sa.String(), nullable=True),
    sa.Column('translator_engine', sa.String(), nullable=True),
    sa.Column('translated_artifact_path', sa.String(), nullable=True),
    sa.Column('translated_artifact_format', sa.String(), nullable=True),
    sa.Column('comic_mode', sa.Boolean(), nullable=True),
    sa.Column('manga_rtl', sa.Boolean(), nullable=True),
    sa.Column('comic_translation_enabled', sa.Boolean(), nullable=True),
    sa.Column('comic_translation_status', sa.String(), nullable=True),
    sa.Column('comic_translation_error', sa.String(), nullable=True),
    sa.Column('comic_translation_artifact_path', sa.String(), nullable=True),
    sa.Column('comic_translation_artifact_format', sa.String(), nullable=True),
    sa.Column('comic_export_status', sa.String(), nullable=True),
    sa.Column('comic_export_path', sa.String(), nullable=True),
    sa.Column('comic_export_source', sa.String(), nullable=True),
    sa.Column('comic_export_error', sa.String(), nullable=True),
    sa.Column('flow_mode', sa.String(), nullable=True),
    sa.Column('active_operation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_id'), ['id'], unique=False)

    op.create_table('stage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('processing_mode', sa.String(), nullable=True),
    sa.Column('input_format', sa.String(), nullable=True),
    sa.Column('translator_engine', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_metrics_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_metrics_job_id'))
        batch_op.drop_index(batch_op.f('ix_stage_metrics_id'))

    op.drop_table('stage_metrics')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_id'))

    op.drop_table('processing_jobs')
    # ### end Alembic commands ###
